pagopa/io-cgn

- apps/card-func/EycaExpired_2_ProcessExpiredEycaQueue/function.json
> fixed trigger queue name

- .changeset/flat-geckos-hug.md
- apps/search-func/Count/__tests__/handler.test.ts
- apps/search-func/Count/function.json
- apps/search-func/Count/handler.ts
- apps/search-func/Count/index.ts
- apps/search-func/RefreshMaterializedViews/__tests__/handler.test.ts
- apps/search-func/RefreshMaterializedViews/handler.ts
- apps/search-func/Search/__tests__/handler.test.ts
- apps/search-func/Search/handler.ts
- apps/search-func/models/CountModel.ts
- apps/search-func/openapi/external.yaml
- apps/search-func/openapi/index.yaml
- apps/search-func/utils/postgres_queries.ts
- added new Count function
- added refresh of merchant view
- fixed Search function to not search if token is less than 3 chars
> [#PE-730] Search endpoint fixes and new Count endpoint

- .changeset/many-scissors-invite.md
- apps/search-func/Count/__tests__/handler.test.ts
- apps/search-func/Count/handler.ts
- apps/search-func/models/CountModel.ts
- apps/search-func/utils/postgres_queries.ts
Extracted count result from array of results.
Query method of sequelize returns an array and not a just a record.
Unit tests.
> Extracted result from array

- .changeset/eight-ties-juggle.md
- apps/search-func/GetMerchant/__tests__/handler.test.ts
- apps/search-func/GetMerchant/handler.ts
- apps/search-func/Search/__tests__/handler.test.ts
- apps/search-func/models/MerchantProfileModel.ts
- apps/search-func/utils/postgres_queries.ts
Fixed code for dropped columns
Dropped columns are breaking the get merchant endpoint
unit tests
> [HOTFIX] Fixed dropped columns

- infra-pe/identity/prod/main.tf
- infra-pe/identity/uat/main.tf
> fix: identity for pe app deployment

- infra-pe/resources/_modules/app_service_attribute_authority/variables.tf
- infra-pe/resources/prod/attribute_authority_ms.tf
- infra-pe/resources/uat/attribute_authority_ms.tf
Added postgres connection string from vault.
App service need to connect to postgres.
Plan
> [#PE-777] Added postgres connection string

- infra-pe/resources/_modules/app_service_onboarding_portal_backend/app_service_onboarding_portal_backend.tf
- infra-pe/resources/_modules/app_service_onboarding_portal_backend/locals.tf
- infra-pe/resources/_modules/app_service_onboarding_portal_backend/main.tf
- infra-pe/resources/_modules/app_service_onboarding_portal_backend/outputs.tf
- infra-pe/resources/_modules/app_service_onboarding_portal_backend/variables.tf
- infra-pe/resources/prod/onboarding_portal_backend_ms.tf
- infra-pe/resources/uat/onboarding_portal_backend_ms.tf
Added new app service module for onboarding-portal-backend
We are migrating to monorepo and ITN our resources.
> [#PE-776] Added onboarding portal backend app service to pe infra

- infra-io/github-runner/prod/main.tf
- infra-io/identity/prod/data.tf
- infra-io/identity/prod/main.tf
- infra-io/resources/_modules/function_app_search/data.tf
- infra-io/resources/_modules/function_app_search/networking.tf
- infra-io/resources/_modules/function_app_search/variables.tf
- infra-io/resources/prod/data.tf
- infra-io/resources/prod/func_search.tf
- infra-io/resources/prod/main.tf
- infra-pe/repository/_modules/repo_environment/README.md
- infra-pe/resources/_modules/app_service_attribute_authority/variables.tf
- infra-pe/resources/prod/.terraform.lock.hcl
Added a private endpoint to link search-func to postgres.
We are migrating to a new db.
Checked reachability from search-func bash shell.
> [#PE-890] Added private endpoint

- infra-pe/resources/_modules/app_service_attribute_authority/additional_peps.tf
- infra-pe/resources/_modules/app_service_onboarding_portal_backend/additional_peps.tf
- infra-pe/resources/_modules/networking/data.tf
- infra-pe/resources/_modules/networking/variables.tf
- infra-pe/resources/_modules/networking/vnet_common.tf
- infra-pe/resources/prod/main.tf
- infra-pe/resources/uat/main.tf
> [PE-881] Allow WEU resources reach ITN app services private endpoints

- infra-pe/resources/_modules/dns/private_dns_zones.tf
- infra-pe/resources/_modules/dns/variables.tf
- infra-pe/resources/prod/data.tf
- infra-pe/resources/prod/main.tf
- infra-pe/resources/uat/data.tf
- infra-pe/resources/uat/main.tf
> [PE-881] Allow WEU resources reach ITN app services private endpoints in prod

- .changeset/large-masks-refuse.md
- apps/attribute-authority-ms/package.json
- apps/attribute-authority-ms/src/services/organizationService.ts
- yarn.lock
Fixed queries to be compliant with PG16.
After migration, these queries where not working.
- Runtime tests pointing to prod env.
- Unit tests
> [PE-910] Fixed query on associations post switch to pg16

- .changeset/cuddly-schools-perform.md
- apps/attribute-authority-ms/src/services/organizationService.ts
- apps/search-func/GetMerchant/handler.ts
- apps/search-func/openapi/external.yaml
- apps/search-func/openapi/index.yaml
- removed required constraint from supportType and supportValue
- added default to spec to serve dummy values
- removed dummy values from function code
We need to dismiss and remove this unused properties.
- unit tests
- build
- lint
> [#PE785] Made supportX properties optional

- infra-io/resources/_modules/function_app_card/function_app_card.tf
- infra-io/resources/_modules/function_app_card/variables.tf
- infra-io/resources/_modules/function_app_merchant/function_app_merchant.tf
- infra-io/resources/_modules/function_app_merchant/variables.tf
- infra-io/resources/_modules/function_app_search/function_app_search.tf
- infra-io/resources/_modules/function_app_search/variables.tf
- infra-io/resources/prod/.terraform.lock.hcl
- infra-io/resources/prod/func_card.tf
- infra-io/resources/prod/func_cgn_commons.tf
- infra-io/resources/prod/func_merchant.tf
- infra-io/resources/prod/func_search.tf
- changed functions module to accept a shared plan and pre-created subnets
- added a new common service plan to host functions
- added a new common subnet
- added a dedicate subnet for search func
We are grouping some azure functions under a shared service plan to reduce costs.
tf plan
> [#PE-932] Created common plan and new subnets for cgn functions

- infra-pe/identity/prod/locals.tf
- infra-pe/identity/uat/locals.tf
> Add owner role to manage locks on cgn-pe resource group in cicd identities

- infra-pe/resources/_modules/cdn/cdn.tf
- infra-pe/resources/_modules/cdn/main.tf
- infra-pe/resources/_modules/cdn/storage_account.tf
- infra-pe/resources/_modules/cdn/variables.tf
- infra-pe/resources/prod/cdn.tf
- infra-pe/resources/uat/cdn.tf
- added new itn storages
- added new itn cdn profile
- added new cdn profile endpoints pointing to storages
We have to migrate to ITN CGN Onboarding Portal Frontend.
> [#PE-925, #PE-927] Added ITN storages, cdn profile and endpoints for cgn portal frontend

- infra-io/resources/_modules/function_app_autoscaler/function_app_autoscaler.tf
- infra-io/resources/_modules/function_app_autoscaler/variables.tf
- infra-io/resources/prod/data.tf
- infra-io/resources/prod/func_cgn_commons.tf
- infra-io/resources/prod/func_search_alerts.tf
Added alerts for apis exposed to App IO
We need to be warned about errors happening to App IO
> [#PE-791] Added alerts for apis exposed to App IO

- infra-pe/identity/prod/locals.tf
- infra-pe/identity/prod/main.tf
- infra-pe/identity/uat/locals.tf
- infra-pe/identity/uat/main.tf
> Allow deploy cdn action to read and write on storage account

- infra-io/resources/_modules/function_app_support/function_app_support.tf
- infra-io/resources/_modules/function_app_support/locals.tf
- infra-io/resources/_modules/function_app_support/main.tf
- infra-io/resources/_modules/function_app_support/outputs.tf
- infra-io/resources/_modules/function_app_support/variables.tf
- infra-io/resources/prod/data.tf
- infra-io/resources/prod/func_card.tf
- infra-io/resources/prod/func_support.tf
- Added new functions app for support.
We need to expose new api to our customer support.
Plan
> [#IOBP-1416] Added infra for func-support

- infra-pe/resources/_modules/cdn/storage_account.tf
- Enabled shared access key
We need to access storages with access key.
> [#IOBP-1437] Enabled shared access key

- apps/support-func/GetUserInfo/index.ts
- apps/support-func/utils/cosmosdb.ts
- apps/support-func/utils/healthcheck.ts
Refactored cosmosdb client to be a singleton
We need to use just one instance of cosmos client.
> [#IOBP-1645] Refactored cosmosdb client to be a singleton
